version: "3.7"
services:
  app:
    image: 'pnm-app:latest'
    build:
      context: .
    container_name: pnm-app
    ports:
      - 8070:8070
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017